### ISSUE TITLE
UniformBuffer seems to be missing from D3D12 branch

### ISSUE THREAD

**Issue by zigguratvertigo** [NVIDIA/Falcor#13]
Hi,

Grabbed the latest code via the zip download github feature. UniformBuffers seem to be missing from this branch.  

\falcor-d3d12\samples\effects\normalmapfiltering\normalmapfiltering.h(48): error C2653: 'UniformBuffer': is not a class or namespace name
\falcor-d3d12\samples\effects\normalmapfiltering\normalmapfiltering.h(48): error C3646: 'mpLightBuffer': unknown override specifier
\falcor-d3d12\samples\effects\normalmapfiltering\normalmapfiltering.h(48): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int

[...]

Similar results when syncing via SourceTree to this specific branch (commit: [ad16784]).

**Comment by nbenty** [comment]
The file was renamed to ConstantBuffer in the D3D12 dev-branch. We were focusing on adding features and cleaning the interfaces, so some of the samples don't work yet.
I'll fix it later this week.

Thanks!

**Comment by nbenty** [comment]
NormalMapFiltering sample is fixed

**Comment by zigguratvertigo** [comment]
Unfortunately, issue still exists if you get the latest d3d12 branch.

**Comment by nbenty** [comment]
Latest NormalMapFiltering.h doesn't have any reference to UniformBuffer.h

[https://github.com/NVIDIA/Falcor/blob/D3D12/Samples/Effects/NormalMapFiltering/NormalMapFiltering.h](url)

**Comment by zigguratvertigo** [comment]
NormalMapFiltering is indeed fixed. :)

I get it in StereoRendering. Seems to be the last one. 

stereorendering.h(50): error C2653: 'UniformBuffer': is not a class or namespace name

**Comment by nbenty** [comment]
The D3D12 branch was merged into master, where I removed StereoRendering from the solution for now. I'll fix it in a few days.
